"""Column-level lineage registry for Bronze -> Silver -> Gold."""

from __future__ import annotations

from dataclasses import dataclass

__all__ = ["LINEAGE_REGISTRY", "LineageEntry"]


@dataclass(frozen=True)
class LineageEntry:
    bronze_table: str
    bronze_column: str
    silver_table: str
    silver_column: str
    gold_table: str | None = None
    gold_column: str | None = None
    transform: str = "passthrough"


def _e(
    bronze_table: str,
    bronze_col: str,
    silver_table: str,
    silver_col: str,
    gold_table: str | None = None,
    gold_col: str | None = None,
    transform: str = "passthrough",
) -> LineageEntry:
    return LineageEntry(
        bronze_table, bronze_col, silver_table, silver_col, gold_table, gold_col, transform
    )


LINEAGE_REGISTRY: list[LineageEntry] = [
    # ── Currencies ──
    _e("erp_currencies", "code", "silver_currencies", "code"),
    _e("erp_currencies", "name", "silver_currencies", "name"),
    _e("erp_currencies", "symbol", "silver_currencies", "symbol"),
    _e("erp_currencies", "decimal_places", "silver_currencies", "decimal_places"),
    _e("erp_currencies", "is_active", "silver_currencies", "is_active"),
    # ── CRM Leads ──
    _e("erp_crm_leads", "tenant_id", "silver_crm_leads", "tenant_id"),
    _e("erp_crm_leads", "id", "silver_crm_leads", "id"),
    _e("erp_crm_leads", "status", "silver_crm_leads", "status", transform="lower"),
    _e("erp_crm_leads", "source", "silver_crm_leads", "source", transform="lower"),
    _e("erp_crm_leads", "first_name", "silver_crm_leads", "first_name", transform="trim"),
    _e("erp_crm_leads", "last_name", "silver_crm_leads", "last_name", transform="trim"),
    _e("erp_crm_leads", "email", "silver_crm_leads", "email", transform="trim"),
    _e("erp_crm_leads", "phone", "silver_crm_leads", "phone", transform="trim"),
    _e("erp_crm_leads", "company", "silver_crm_leads", "company", transform="trim"),
    _e("erp_crm_leads", "owner_id", "silver_crm_leads", "owner_id"),
    _e("erp_crm_leads", "team_id", "silver_crm_leads", "team_id"),
    _e("erp_crm_leads", "created_at", "silver_crm_leads", "created_at"),
    _e("erp_crm_leads", "updated_at", "silver_crm_leads", "updated_at"),
    # ── CRM Opportunities ──
    _e("erp_crm_opportunities", "tenant_id", "silver_crm_opportunities", "tenant_id"),
    _e("erp_crm_opportunities", "id", "silver_crm_opportunities", "id"),
    _e("erp_crm_opportunities", "name", "silver_crm_opportunities", "name", transform="trim"),
    _e("erp_crm_opportunities", "lead_id", "silver_crm_opportunities", "lead_id"),
    _e("erp_crm_opportunities", "stage", "silver_crm_opportunities", "stage", transform="lower"),
    _e(
        "erp_crm_opportunities",
        "amount",
        "silver_crm_opportunities",
        "amount",
        transform="numeric_18_4",
    ),
    _e(
        "erp_crm_opportunities",
        "currency_code",
        "silver_crm_opportunities",
        "currency_code",
        transform="coalesce_USD",
    ),
    _e("erp_crm_opportunities", "probability", "silver_crm_opportunities", "probability"),
    _e(
        "erp_crm_opportunities",
        "expected_close_date",
        "silver_crm_opportunities",
        "expected_close_date",
    ),
    _e("erp_crm_opportunities", "owner_id", "silver_crm_opportunities", "owner_id"),
    _e("erp_crm_opportunities", "team_id", "silver_crm_opportunities", "team_id"),
    _e("erp_crm_opportunities", "won_at", "silver_crm_opportunities", "won_at"),
    _e("erp_crm_opportunities", "lost_at", "silver_crm_opportunities", "lost_at"),
    _e("erp_crm_opportunities", "lost_reason", "silver_crm_opportunities", "lost_reason"),
    _e("erp_crm_opportunities", "created_at", "silver_crm_opportunities", "created_at"),
    _e("erp_crm_opportunities", "updated_at", "silver_crm_opportunities", "updated_at"),
    # ── CRM Customers ──
    _e("erp_crm_customers", "tenant_id", "silver_crm_customers", "tenant_id"),
    _e("erp_crm_customers", "id", "silver_crm_customers", "id"),
    _e(
        "erp_crm_customers",
        "customer_code",
        "silver_crm_customers",
        "customer_code",
        transform="trim",
    ),
    _e("erp_crm_customers", "name", "silver_crm_customers", "name", transform="trim"),
    _e("erp_crm_customers", "email", "silver_crm_customers", "email", transform="trim"),
    _e("erp_crm_customers", "phone", "silver_crm_customers", "phone", transform="trim"),
    _e(
        "erp_crm_customers",
        "credit_limit",
        "silver_crm_customers",
        "credit_limit",
        transform="numeric_18_4",
    ),
    _e(
        "erp_crm_customers",
        "currency_code",
        "silver_crm_customers",
        "currency_code",
        transform="coalesce_USD",
    ),
    _e("erp_crm_customers", "is_active", "silver_crm_customers", "is_active"),
    _e(
        "erp_crm_customers",
        "source_opportunity_id",
        "silver_crm_customers",
        "source_opportunity_id",
    ),
    _e("erp_crm_customers", "created_at", "silver_crm_customers", "created_at"),
    _e("erp_crm_customers", "updated_at", "silver_crm_customers", "updated_at"),
    # ── Sales Orders ──
    _e("erp_sales_orders", "tenant_id", "silver_sales_orders", "tenant_id"),
    _e("erp_sales_orders", "id", "silver_sales_orders", "id"),
    _e("erp_sales_orders", "order_number", "silver_sales_orders", "order_number", transform="trim"),
    _e("erp_sales_orders", "customer_id", "silver_sales_orders", "customer_id"),
    _e("erp_sales_orders", "status", "silver_sales_orders", "status", transform="lower"),
    _e("erp_sales_orders", "subtotal", "silver_sales_orders", "subtotal", transform="numeric_18_4"),
    _e("erp_sales_orders", "discount", "silver_sales_orders", "discount", transform="numeric_18_4"),
    _e("erp_sales_orders", "tax", "silver_sales_orders", "tax", transform="numeric_18_4"),
    _e("erp_sales_orders", "total", "silver_sales_orders", "total", transform="numeric_18_4"),
    _e(
        "erp_sales_orders",
        "currency_code",
        "silver_sales_orders",
        "currency_code",
        transform="coalesce_USD",
    ),
    _e("erp_sales_orders", "order_date", "silver_sales_orders", "order_date"),
    _e("erp_sales_orders", "created_at", "silver_sales_orders", "created_at"),
    _e("erp_sales_orders", "updated_at", "silver_sales_orders", "updated_at"),
    # ── Sales Order Lines ──
    _e("erp_sales_order_lines", "tenant_id", "silver_sales_order_lines", "tenant_id"),
    _e("erp_sales_order_lines", "id", "silver_sales_order_lines", "id"),
    _e("erp_sales_order_lines", "order_id", "silver_sales_order_lines", "order_id"),
    _e("erp_sales_order_lines", "product_id", "silver_sales_order_lines", "product_id"),
    _e("erp_sales_order_lines", "quantity", "silver_sales_order_lines", "quantity"),
    _e(
        "erp_sales_order_lines",
        "unit_price",
        "silver_sales_order_lines",
        "unit_price",
        transform="numeric_18_4",
    ),
    _e(
        "erp_sales_order_lines",
        "discount",
        "silver_sales_order_lines",
        "discount",
        transform="numeric_18_4",
    ),
    _e("erp_sales_order_lines", "tax", "silver_sales_order_lines", "tax", transform="numeric_18_4"),
    _e(
        "erp_sales_order_lines",
        "line_total",
        "silver_sales_order_lines",
        "line_total",
        transform="numeric_18_4",
    ),
    _e(
        "erp_sales_order_lines",
        "currency_code",
        "silver_sales_order_lines",
        "currency_code",
        transform="coalesce_USD",
    ),
    _e("erp_sales_order_lines", "created_at", "silver_sales_order_lines", "created_at"),
    _e("erp_sales_order_lines", "updated_at", "silver_sales_order_lines", "updated_at"),
    # ── Invoices ──
    _e("erp_invoices", "tenant_id", "silver_invoices", "tenant_id"),
    _e("erp_invoices", "id", "silver_invoices", "id"),
    _e("erp_invoices", "invoice_number", "silver_invoices", "invoice_number", transform="trim"),
    _e("erp_invoices", "customer_id", "silver_invoices", "customer_id"),
    _e("erp_invoices", "order_id", "silver_invoices", "order_id"),
    _e("erp_invoices", "invoice_date", "silver_invoices", "invoice_date"),
    _e("erp_invoices", "due_date", "silver_invoices", "due_date"),
    _e("erp_invoices", "status", "silver_invoices", "status", transform="lower"),
    _e("erp_invoices", "subtotal", "silver_invoices", "subtotal", transform="numeric_18_4"),
    _e("erp_invoices", "tax", "silver_invoices", "tax", transform="numeric_18_4"),
    _e("erp_invoices", "total", "silver_invoices", "total", transform="numeric_18_4"),
    _e(
        "erp_invoices",
        "currency_code",
        "silver_invoices",
        "currency_code",
        transform="coalesce_USD",
    ),
    _e(
        "erp_invoices",
        "exchange_rate",
        "silver_invoices",
        "exchange_rate",
        transform="numeric_18_4",
    ),
    _e("erp_invoices", "source", "silver_invoices", "source", transform="lower"),
    _e("erp_invoices", "source_ref", "silver_invoices", "source_ref"),
    _e("erp_invoices", "created_at", "silver_invoices", "created_at"),
    _e("erp_invoices", "updated_at", "silver_invoices", "updated_at"),
    # ── Payments ──
    _e("erp_payments", "tenant_id", "silver_payments", "tenant_id"),
    _e("erp_payments", "id", "silver_payments", "id"),
    _e("erp_payments", "payment_number", "silver_payments", "payment_number", transform="trim"),
    _e("erp_payments", "invoice_id", "silver_payments", "invoice_id"),
    _e("erp_payments", "customer_id", "silver_payments", "customer_id"),
    _e("erp_payments", "amount", "silver_payments", "amount", transform="numeric_18_4"),
    _e(
        "erp_payments",
        "currency_code",
        "silver_payments",
        "currency_code",
        transform="coalesce_USD",
    ),
    _e("erp_payments", "method", "silver_payments", "method", transform="lower"),
    _e("erp_payments", "status", "silver_payments", "status", transform="lower"),
    _e("erp_payments", "payment_date", "silver_payments", "payment_date"),
    _e("erp_payments", "source", "silver_payments", "source", transform="lower"),
    _e("erp_payments", "source_ref", "silver_payments", "source_ref"),
    _e("erp_payments", "created_at", "silver_payments", "created_at"),
    _e("erp_payments", "updated_at", "silver_payments", "updated_at"),
    # ── Journal Lines ──
    _e("erp_journal_lines", "tenant_id", "silver_journal_lines", "tenant_id"),
    _e("erp_journal_lines", "id", "silver_journal_lines", "id"),
    _e("erp_journal_lines", "entry_id", "silver_journal_lines", "entry_id"),
    _e("erp_journal_lines", "account_id", "silver_journal_lines", "account_id"),
    _e("erp_journal_lines", "description", "silver_journal_lines", "description"),
    _e("erp_journal_lines", "debit", "silver_journal_lines", "debit", transform="numeric_18_4"),
    _e("erp_journal_lines", "credit", "silver_journal_lines", "credit", transform="numeric_18_4"),
    _e(
        "erp_journal_lines",
        "currency_code",
        "silver_journal_lines",
        "currency_code",
        transform="coalesce_USD",
    ),
    _e(
        "erp_journal_lines",
        "exchange_rate",
        "silver_journal_lines",
        "exchange_rate",
        transform="numeric_18_4",
    ),
    _e("erp_journal_lines", "created_at", "silver_journal_lines", "created_at"),
    _e("erp_journal_lines", "updated_at", "silver_journal_lines", "updated_at"),
    # ── Products ──
    _e("erp_products", "tenant_id", "silver_products", "tenant_id"),
    _e("erp_products", "id", "silver_products", "id"),
    _e("erp_products", "sku", "silver_products", "sku", transform="trim"),
    _e("erp_products", "name", "silver_products", "name", transform="trim"),
    _e("erp_products", "description", "silver_products", "description"),
    _e("erp_products", "cost_price", "silver_products", "cost_price", transform="numeric_18_4"),
    _e(
        "erp_products",
        "cost_currency_code",
        "silver_products",
        "cost_currency_code",
        transform="coalesce_USD",
    ),
    _e("erp_products", "sell_price", "silver_products", "sell_price", transform="numeric_18_4"),
    _e(
        "erp_products",
        "sell_currency_code",
        "silver_products",
        "sell_currency_code",
        transform="coalesce_USD",
    ),
    _e("erp_products", "is_active", "silver_products", "is_active"),
    _e("erp_products", "reorder_point", "silver_products", "reorder_point"),
    _e("erp_products", "supplier_id", "silver_products", "supplier_id"),
    _e("erp_products", "created_at", "silver_products", "created_at"),
    _e("erp_products", "updated_at", "silver_products", "updated_at"),
    # ── Silver -> Gold (key lineage) ──
    _e(
        "erp_crm_customers",
        "id",
        "silver_crm_customers",
        "id",
        "gold_dim_customer",
        "customer_key",
        "uuid5",
    ),
    _e("erp_products", "id", "silver_products", "id", "gold_dim_product", "product_key", "uuid5"),
    _e(
        "erp_crm_opportunities",
        "id",
        "silver_crm_opportunities",
        "id",
        "gold_fact_deals",
        "deal_key",
        "uuid5",
    ),
    _e(
        "erp_crm_opportunities",
        "id",
        "silver_crm_opportunities",
        "id",
        "gold_fact_pipeline",
        "pipeline_key",
        "uuid5",
    ),
    _e("erp_invoices", "id", "silver_invoices", "id", "gold_fact_revenue", "revenue_key", "uuid5"),
    # ── Gold money columns trace to Silver ──
    _e(
        "erp_invoices",
        "total",
        "silver_invoices",
        "total",
        "gold_fact_revenue",
        "total",
        "numeric_18_4",
    ),
    _e(
        "erp_payments",
        "amount",
        "silver_payments",
        "amount",
        "gold_fact_revenue",
        "payment_total",
        "sum_aggregate",
    ),
    _e(
        "erp_crm_opportunities",
        "amount",
        "silver_crm_opportunities",
        "amount",
        "gold_fact_deals",
        "amount",
        "numeric_18_4",
    ),
    _e(
        "erp_crm_opportunities",
        "amount",
        "silver_crm_opportunities",
        "amount",
        "gold_fact_pipeline",
        "amount",
        "numeric_18_4",
    ),
]
